// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/billing': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/billing.get').default>>>>
    }
    '/api/admin/chats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/chats.get').default>>>>
    }
    '/api/admin/content-stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/content-stats.get').default>>>>
    }
    '/api/admin/leads': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/leads.get').default>>>>
    }
    '/api/admin/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/login.post').default>>>>
    }
    '/api/admin/overview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/overview.get').default>>>>
    }
    '/api/admin/tenants': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants.post').default>>>>
    }
    '/api/admin/tenants/:tenantId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId].put').default>>>>
    }
    '/api/admin/tenants/:tenantId/agent-docs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/agent-docs.get').default>>>>
    }
    '/api/admin/tenants/:tenantId/agent-docs/:fileName': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/agent-docs/[fileName].put').default>>>>
    }
    '/api/admin/tenants/:tenantId/index-stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/index-stats.get').default>>>>
    }
    '/api/admin/tenants/:tenantId/jobs': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/jobs.get').default>>>>
    }
    '/api/admin/tenants/:tenantId/jobs/:jobId/retry': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/jobs/[jobId]/retry.post').default>>>>
    }
    '/api/admin/tenants/:tenantId/jobs/reindex': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/jobs/reindex.post').default>>>>
    }
    '/api/admin/tenants/:tenantId/reset-code': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/reset-code.post').default>>>>
    }
    '/api/admin/tenants/:tenantId/restore': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/restore.post').default>>>>
    }
    '/api/admin/tenants/:tenantId/sources': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/sources.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/sources.post').default>>>>
    }
    '/api/admin/tenants/:tenantId/sources/:sourceId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/sources/[sourceId].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/sources/[sourceId].put').default>>>>
    }
    '/api/admin/tenants/:tenantId/sources/:sourceId/sync': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/sources/[sourceId]/sync.post').default>>>>
    }
    '/api/admin/tenants/:tenantId/sources/:sourceId/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/sources/[sourceId]/upload.post').default>>>>
    }
    '/api/admin/tenants/:tenantId/training': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/tenants/[tenantId]/training.post').default>>>>
    }
    '/api/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat.post').default>>>>
    }
    '/api/contact': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact.post').default>>>>
    }
    '/api/embed/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/embed/config.get').default>>>>
    }
    '/api/tenant/change-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tenant/change-password.post').default>>>>
    }
    '/api/tenant/chats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tenant/chats.get').default>>>>
    }
    '/api/tenant/leads': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tenant/leads.get').default>>>>
    }
    '/api/tenant/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tenant/login.post').default>>>>
    }
    '/api/tenant/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tenant/logout.post').default>>>>
    }
    '/api/tenant/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tenant/me.get').default>>>>
    }
    '/api/tenant/overview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tenant/overview.get').default>>>>
    }
    '/api/tenant/reset-code': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tenant/reset-code.post').default>>>>
    }
    '/api/tenant/reset-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tenant/reset-password.post').default>>>>
    }
    '/customer-bot.js': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/customer-bot.js.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}